### PR TITLE
Removed Pinned Provider

### PR DESCRIPTION
**Pull request by hsanjuan**
I'm going to remove my blocker by using this version of reprovider which does not import `go-ipfs` (I think the import in go.mod was spurious though since the Pinner interface was moved here).

In any case, I think the PinnedProvider should be go-ipfs specific concept and stay in go-ipfs for the moment.

### CODE REVIEW

**Comment by michaelavila** [comment]
@hsanjuan thanks for the PR. As it turns out I actually removed the dependence on `pin.Pinner` without removing the `PinnedProvider` (just yet anyway). I just didn't actually update `go.mod` my apologies.

Can we only merge the `go.mod` and `go.sum` changes with this PR? And not the removing of the `PinnedProvider`.

**Review by michaelavila — CHANGES_REQUESTED** [review]
@hsanjuan thanks for the PR. As it turns out I actually removed the dependence on `Pinner` without removing the `PinnedProvider` (just yet anyway). I just didn't update `go.mod`, my apologies.

Can we only merge the `go.mod` and `go.sum` changes in this PR? Basically, just merge commit b903c32?

I'm not opposed to moving the pinner stuff back into go-ipfs, I just have a lot of stuff up in the air right now and want to spend time doing that move once I get the module itself separated and integrated with the work I've had in progress for a while.

**Comment by hsanjuan** [comment]
@michaelavila yeah that sounds good

**Comment by michaelavila** [comment]
@hsanjuan thank you

**Pull request closed without merging**
